apiVersion: "cert-manager.io/v1"
kind: "Certificate"
metadata:
  name: "wordpress-tls"
  namespace: "wordpress"
spec:
  secretName: "wordpress-tls"
  dnsNames: ["wordpress.example.com"]
  issuerRef:
    name: "letsencrypt-prod"
    kind: "ClusterIssuer"
