apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: bitnami/wordpress:5
        resources:
          requests:
            cpu: 1000m
          limits:
            cpu: 1000m
        name: wordpress
        env:
        - name: WORDPRESS_DATABASE_HOST
          value: mysql
        - name: WORDPRESS_DATABASE_PORT_NUMBER
          value: "3306"
        - name: WORDPRESS_DATABASE_NAME
          value: wordpress
        - name: WORDPRESS_DATABASE_USER
          value: username
        - name: WORDPRESS_DATABASE_PASSWORD
          value: password
        - name: WORDPRESS_USERNAME
          value: admin
        - name: WORDPRESS_PASSWORD
          value: admin
        ports:
        - containerPort: 8080
          name: wordpress
